image: php:7.1.1
pipelines:
  default:
    - step:
        script:
          - composer install --prefer-source --no-interaction --dev
          - vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=./vendor/* ./